### ISSUE TITLE
Update component styles

### ISSUE THREAD

**Issue by lvwzhen** [sailboatui/sailboatui#56]
### Describe the solution you'd like

Optimization of component styles to give a more consistent and standardized style.

## TODO

- [ ] #57
- [ ] [Alert](https://sailboatui.com/docs/components/alert/)
- [ ] [Avatar](https://sailboatui.com/docs/components/avatar/)
- [ ] [Badge](https://sailboatui.com/docs/components/badge/)
- [ ] [Breadcrumb](https://sailboatui.com/docs/components/breadcrumb/)
- [ ] [Button](https://sailboatui.com/docs/components/button/)
- [ ] [Button Group](https://sailboatui.com/docs/components/button-group/)
- [ ] [Card](https://sailboatui.com/docs/components/card/)
- [ ] [Divider](https://sailboatui.com/docs/components/divider/)
- [ ] [Dropdown](https://sailboatui.com/docs/components/dropdown/)
- [ ] [Layout](https://sailboatui.com/docs/components/layout/)
- [ ] [List](https://sailboatui.com/docs/components/list/)
- [ ] [Media Object](https://sailboatui.com/docs/components/media-object/)
- [ ] [Modal](https://sailboatui.com/docs/components/modal/)
- [ ] [Notification](https://sailboatui.com/docs/components/notification/)
- [ ] [Pagination](https://sailboatui.com/docs/components/pagination/)
- [ ] [Progress](https://sailboatui.com/docs/components/progress/)
- [ ] [Tab](https://sailboatui.com/docs/components/tab/)
- [ ] [Table](https://sailboatui.com/docs/components/table/)
- [ ] [Tooltip](https://sailboatui.com/docs/components/tooltip/)
- [ ] [Checkbox](https://sailboatui.com/docs/forms/checkbox/)
- [ ] [File Input](https://sailboatui.com/docs/forms/file-input/)
- [ ] [Form Layout](https://sailboatui.com/docs/forms/form-layout/)
- [ ] [Input](https://sailboatui.com/docs/forms/input/)
- [ ] [Radio](https://sailboatui.com/docs/forms/radio/)
- [ ] [Select](https://sailboatui.com/docs/forms/select/)
- [ ] [Textarea](https://sailboatui.com/docs/forms/textarea/)
- [ ] [Toggle](https://sailboatui.com/docs/forms/toggle/)
